language: c
sudo: true
os: osx
osx_image: xcode7.2
before_install:
  - brew update
  - clear
  - export THEOS=/opt/theos

script: "sudo python get-pip.py && ./Setup.sh && ./InstallTheos.sh &&./build.py DEBUG"