language: c
sudo: true
os: osx
osx_image: xcode7.2
before_install:
  - brew update
  - clear

script: "sudo python get-pip.py && ./Setup.sh && ./InstallTheos.sh && export THEOS_VENDOR_INCLUDE_PATH=/opt/theos/vendor/include&& export THEOS_VENDOR_LIBRARY_PATH=/opt/theos/vendor/lib &&./build.py DEBUG PROTOTYPE"